"""init

Revision ID: 73ce66aaf7fd
Revises: 
Create Date: 2026-02-21 03:06:24.381410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73ce66aaf7fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selfheal_log')
    op.drop_table('reports')
    op.drop_table('rules')
    op.drop_table('events')
    op.drop_table('trust_scores')
    op.drop_table('system_health')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_health',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_score', mysql.FLOAT(), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.Column('total_healed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trust_scores',
    sa.Column('device_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('trust_score', mysql.FLOAT(), nullable=True),
    sa.Column('anomaly_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_threat', mysql.DATETIME(), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('src_ip', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('dst_ip', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protocol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('attack_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('confidence', mysql.FLOAT(), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('agent', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('reasoning', mysql.TEXT(), nullable=True),
    sa.Column('resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rules',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('rule_text', mysql.TEXT(), nullable=True),
    sa.Column('iptables_cmd', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('human_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('rules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reports',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('generated_at', mysql.DATETIME(), nullable=True),
    sa.Column('time_window', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('correlations', mysql.TEXT(), nullable=True),
    sa.Column('predicted_next', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('selfheal_log',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('incident_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('triggered_at', mysql.DATETIME(), nullable=True),
    sa.Column('health_score_before', mysql.FLOAT(), nullable=True),
    sa.Column('health_score_after', mysql.FLOAT(), nullable=True),
    sa.Column('permanent_rules', mysql.TEXT(), nullable=True),
    sa.Column('lessons_learned', mysql.TEXT(), nullable=True),
    sa.Column('hardening_recommendations', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
